
import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Velocity Running Shorts',
    slug: 'velocity-running-shorts',
    description: 'Lightweight and breathable, these shorts are designed for maximum speed and comfort. Features a secure zip pocket for your essentials.',
    price: 25000.00,
    images: [
      { src: '/man_running_shorts.jpg', alt: 'Man running in black shorts', aiHint: 'running shorts' },
      { src: '/gemini_1.png', alt: 'Close up of short fabric', aiHint: 'shorts detail' },
      { src: '/gemini_2.png', alt: 'Back view of shorts', aiHint: 'running shorts' },
    ],
    category: 'Men',
    tags: ['running', 'shorts', 'men', 'performance'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#000000', '#3B82F6', '#9CA3AF'],
  },
  {
    id: '2',
    name: 'Zenith Yoga Leggings',
    slug: 'zenith-yoga-leggings',
    description: 'Experience ultimate flexibility with our Zenith Yoga Leggings. The high-waisted design and four-way stretch fabric move with you.',
    price: 38000.00,
    images: [
      { src: '/gemini_3.png', alt: 'Woman in yoga pose wearing leggings', aiHint: 'yoga leggings' },
      { src: '/gemini_4.png', alt: 'Fabric detail of yoga leggings', aiHint: 'leggings fabric' },
      // { src: 'https://picsum.photos/seed/p2-3/1200/1200', alt: 'Side view of leggings', aiHint: 'yoga leggings' },
    ],
    category: 'Women',
    tags: ['yoga', 'leggings', 'women', 'comfort'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#2E1F3C', '#E11D48', '#16A34A'],
  },
  {
    id: '3',
    name: 'Apex Performance Tee',
    slug: 'apex-performance-tee',
    description: 'A high-performance tee that keeps you cool and dry. Its moisture-wicking technology is perfect for intense workouts.',
    price: 20000.00,
    images: [
      { src: '/gemini_5.png', alt: 'Man wearing a performance t-shirt', aiHint: 'performance shirt' },
      { src: '/gemini_6.png', alt: 'Close up of shirt fabric', aiHint: 'shirt fabric' },
    ],
    category: 'Men',
    tags: ['training', 'shirt', 'men', 'performance'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#FFFFFF', '#111827', '#BE123C'],
  },
  {
    id: '4',
    name: 'Momentum Training Jacket',
    slug: 'momentum-training-jacket',
    description: 'A versatile, weather-resistant jacket for your outdoor training sessions. Lightweight but warm, it\'s the perfect outer layer.',
    price: 55000.00,
    images: [
      { src: '/gemini_7.png', alt: 'Man wearing a training jacket', aiHint: 'training jacket' },
      { src: '/gemini_8.png', alt: 'Jacket zipper detail', aiHint: 'jacket detail' },
    ],
    category: 'Men',
    tags: ['jacket', 'training', 'men', 'outerwear'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#1F2937', '#4F46E5'],
  },
  {
    id: '5',
    name: 'Flow Seamless Bra',
    slug: 'flow-seamless-bra',
    description: 'Designed for low-impact activities like yoga and pilates, this seamless bra offers light support and maximum comfort.',
    price: 22000.00,
    images: [
      { src: '/gemini_9.png', alt: 'Woman wearing a seamless sports bra', aiHint: 'sports bra' },
      { src: '/gemini_10.png', alt: 'Back of sports bra', aiHint: 'sports bra back' },
    ],
    category: 'Women',
    tags: ['bra', 'yoga', 'women', 'comfort'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#F3F4F6', '#FBCFE8', '#A78BFA'],
  },
  {
    id: '6',
    name: 'React Compression Tights',
    slug: 'react-compression-tights',
    description: 'Enhance your performance and recovery with our React Compression Tights, designed to support your muscles during high-intensity exercise.',
    price: 42000.00,
    images: [
      { src: '/gemini_11.png', alt: 'Man wearing compression tights', aiHint: 'compression tights' },
      { src: '/gemini_12.png', alt: 'Detail of compression fabric', aiHint: 'tights fabric' },
    ],
    category: 'Men',
    tags: ['tights', 'running', 'men', 'compression'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#000000', '#4B5563'],
  },
  {
    id: '7',
    name: 'Stratus Windbreaker',
    slug: 'stratus-windbreaker',
    description: 'An ultra-lightweight, packable windbreaker for women. Perfect for windy runs or as an emergency layer.',
    price: 50000.00,
    images: [
      { src: '/gemini_5.png', alt: 'Woman wearing a windbreaker jacket', aiHint: 'windbreaker jacket' },
      { src: '/gemini_7.png', alt: 'Windbreaker packed into its pocket', aiHint: 'jacket packed' },
    ],
    category: 'Women',
    tags: ['jacket', 'running', 'women', 'outerwear'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#ECFDF5', '#FEF2F2', '#EFF6FF'],
  },
  {
    id: '8',
    name: 'Endurance Sports Cap',
    slug: 'endurance-sports-cap',
    description: 'Keep the sun and sweat out of your eyes with this quick-drying, breathable sports cap. Features an adjustable strap for a perfect fit.',
    price: 15000.00,
    images: [
      { src: '/gemini_12.png', alt: 'A sports cap', aiHint: 'sports cap' },
      { src: '/gemini_11.png', alt: 'Adjustable strap of the cap', aiHint: 'cap detail' },
    ],
    category: 'Accessories',
    tags: ['cap', 'running', 'accessory', 'unisex'],
    sizes: ['One Size'],
    colors: ['#FFFFFF', '#000000', '#ffe600'],
  },
];

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find(p => p.slug === slug);
};
